// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Migrate/Studio need a direct (non-pooled) connection — Neon's pooled
    // "-pooler" endpoint doesn't support the advisory locks Migrate uses.
    // The app runtime uses DATABASE_URL (pooled) via @prisma/adapter-neon instead.
    url: process.env["DIRECT_URL"] ?? process.env["DATABASE_URL"],
  },
});
